{{- if .Values.serviceAccount.create }}
{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "spring-hello-chart.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spring-hello-chart.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "spring-hello-chart.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "spring-hello-chart.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
