name: CI/CD Pipeline

on:
  push:
    branches:
      - "main"

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  IMAGE_NAME: spring-hello-problem

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 新增的缓存步骤
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          # Maven 本地仓库的路径
          path: ~/.m2/repository
          # 缓存键，用于识别缓存版本。这里结合了 runner 的 OS 和 pom.xml 的 hash
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          # 如果 key 不匹配，则尝试使用 restore-keys 恢复最近的缓存
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  helm-validation:
    # 这个任务将在 build-and-push 任务成功后运行
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 步骤 1: 安装 Kind 和 Kubectl
      - name: Install Kind and Kubectl
        run: |
          # 下载并安装 Kind
          curl -Lo kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

          # 下载并安装 Kubectl
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      # 步骤 2: 创建 Kind 集群
      - name: Create Kind cluster
        run: kind create cluster

      # 步骤 3: 安装 Helm
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.10.0'

      # 使用现成的 action 来安装 Helm
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.10.0' # 确保使用一个兼容你集群的版本

      - name: Set Helm chart path
        id: chart
        run: echo "CHART_PATH=./spring-hello-chart" >> $GITHUB_ENV

      - name: Helm lint (语法和最佳实践检查)
        run: helm lint ${{ env.CHART_PATH }}

      - name: Helm dry-run (模板渲染和值验证)
        # --dry-run --debug 模拟部署，并打印所有生成的 YAML
        # --set 参数用于动态覆盖 values.yaml 中的 image.tag
        run: |
          IMAGE_TAG="${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          helm install my-app ${{ env.CHART_PATH }} \
          --dry-run \
          --debug \
          --set image.tag=${{ github.sha }} \
          --namespace my-app
